# Generated by Django 3.2.5 on 2021-08-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislikearticle',
            name='owner_object',
        ),
        migrations.RemoveField(
            model_name='dislikearticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dislikearticlecomment',
            name='owner_object',
        ),
        migrations.RemoveField(
            model_name='dislikearticlecomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likearticle',
            name='owner_object',
        ),
        migrations.RemoveField(
            model_name='likearticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='likearticlecomment',
            name='owner_object',
        ),
        migrations.RemoveField(
            model_name='likearticlecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentArticle',
        ),
        migrations.DeleteModel(
            name='DislikeArticle',
        ),
        migrations.DeleteModel(
            name='DislikeArticleComment',
        ),
        migrations.DeleteModel(
            name='LikeArticle',
        ),
        migrations.DeleteModel(
            name='LikeArticleComment',
        ),
    ]
