# Generated by Django 3.2.5 on 2021-08-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedArticles',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_web.article')),
            ],
            bases=('main_web.article',),
        ),
    ]
