# Generated by Django 3.2.5 on 2021-08-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_web', '0002_auto_20210823_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creating', models.DateTimeField(auto_now_add=True)),
                ('comment_text', models.TextField(max_length=5000, null=True)),
                ('owner_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_creating'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creating', models.DateTimeField(auto_now_add=True)),
                ('owner_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.commentarticle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_creating'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creating', models.DateTimeField(auto_now_add=True)),
                ('owner_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_creating'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DislikeArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creating', models.DateTimeField(auto_now_add=True)),
                ('owner_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.commentarticle')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_creating'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DislikeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_creating', models.DateTimeField(auto_now_add=True)),
                ('owner_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_creating'],
                'abstract': False,
            },
        ),
    ]
