# Generated by Django 3.2.5 on 2021-08-23 22:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_web', '0003_commentarticle_dislikearticle_dislikearticlecomment_likearticle_likearticlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dislikearticle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dislikearticlecomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likearticle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='likearticlecomment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dislikearticle',
            unique_together={('user', 'owner_object')},
        ),
        migrations.AlterUniqueTogether(
            name='dislikearticlecomment',
            unique_together={('user', 'owner_object')},
        ),
        migrations.AlterUniqueTogether(
            name='likearticle',
            unique_together={('user', 'owner_object')},
        ),
        migrations.AlterUniqueTogether(
            name='likearticlecomment',
            unique_together={('user', 'owner_object')},
        ),
    ]
