# Generated by Django 3.2.5 on 2021-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0003_auto_20210723_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.RemoveField(
            model_name='article',
            name='cat',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=10000),
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ManyToManyField(to='main_web.Category'),
        ),
    ]
