# Generated by Django 3.2.5 on 2021-08-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0003_auto_20210812_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['data_post']},
        ),
    ]
