# Generated by Django 3.2.5 on 2021-08-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0004_auto_20210823_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSiteObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AddField(
            model_name='article',
            name='basesiteobject_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main_web.basesiteobject'),
            preserve_default=False,
        ),
    ]
