# Generated by Django 3.2.5 on 2021-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_auto_20210824_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='basesiteobject_ptr',
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
