# Generated by Django 3.2.5 on 2021-08-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0006_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
