# Generated by Django 3.2.5 on 2021-08-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0007_auto_20210824_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['data_post']},
        ),
    ]
