# Generated by Django 3.2.5 on 2021-08-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-data_post', '-time_post']},
        ),
    ]
