# Generated by Django 3.2.5 on 2021-08-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0010_auto_20210819_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_profile',
        ),
    ]
