# Generated by Django 3.2.5 on 2021-08-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0012_auto_20210819_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_registraton',
            new_name='date_registration',
        ),
    ]
