# Generated by Django 3.2.5 on 2021-08-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0013_rename_date_registraton_userprofile_date_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='articles_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diselikes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
