# Generated by Django 3.2.5 on 2021-08-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0014_auto_20210821_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='articles_count',
            new_name='user_articles_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='comments_count',
            new_name='user_comments_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='diselikes_count',
            new_name='user_diselikes_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='likes_count',
            new_name='user_likes_count',
        ),
    ]
