# Generated by Django 3.2.5 on 2021-08-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0015_auto_20210821_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
